/**
 * History bundles: the adversary classes, as verdicts.
 * Run: `npm run build && node --test dist/transparency-history.test.js`.
 *
 * The corpus in test-vectors/transparency/adversary is generated by a Python
 * script that asserts the Python verifier's verdict before writing each file.
 * This test holds the TypeScript verifier to the same verdicts, and the interop
 * sweep holds both CLIs to them too. A verdict is a name, not a boolean, and
 * the two implementations must agree on the name.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { assessHistory } from './transparency.js';

const ADV = join(process.cwd(), '..', '..', 'test-vectors', 'transparency', 'adversary');
const files = existsSync(ADV) ? readdirSync(ADV).filter((f) => f.endsWith('.json')).sort() : [];
const load = (f: string) => JSON.parse(readFileSync(join(ADV, f), 'utf8'));

test('the adversary corpus is present', () => {
  assert.ok(files.length >= 11, `expected the corpus at ${ADV}`);
});

for (const f of files) {
  test(`adversary/${f} reaches its expected verdict`, () => {
    const b = load(f);
    const r = assessHistory(b, b.trusted_public_key);
    assert.equal(r.verdict, b.expect.verdict, r.reason);
    assert.equal(r.valid, r.verdict === 'consistent');
  });
}

test('lag is not backdating: pinned as consistent, so nobody improves it away', () => {
  const b = load('a3-lag-is-not-backdating.json');
  assert.equal(assessHistory(b, b.trusted_public_key).verdict, 'consistent');
});

test('precedence: equivocation outranks a fork when a bundle carries both', () => {
  const eq = load('a1-equivocation-same-size.json');
  const fork = load('a1-fork-no-extension.json');
  const both = { heads: [...eq.heads, ...fork.heads], consistency: fork.consistency };
  assert.equal(assessHistory(both, eq.trusted_public_key).verdict, 'equivocation');
});

test('a per-org head is refused in a bundle: only public heads carry a timestamp', () => {
  const b = load('a1-consistent-growth.json');
  const { log: _log, ...h } = b.heads[0];
  const r = assessHistory({ heads: [{ ...h, org_id: 'org-x' }] }, b.trusted_public_key);
  assert.equal(r.verdict, 'invalid_head');
});
