"""History bundles: the adversary classes, as verdicts.

The bundle corpus in test-vectors/transparency/adversary is generated by a
script that asserts this implementation's verdict before writing each file,
so this test is the guard against the implementation drifting away from the
corpus after the fact. The interop sweep holds the TypeScript verifier to the
same verdicts.
"""
import json
import pathlib

import pytest

from aqta_verify_receipt.transparency import assess_history

ADV = pathlib.Path(__file__).resolve().parents[3] / "test-vectors" / "transparency" / "adversary"
BUNDLES = sorted(ADV.glob("*.json")) if ADV.exists() else []


@pytest.mark.parametrize("path", BUNDLES, ids=[p.name for p in BUNDLES])
def test_every_bundle_reaches_its_expected_verdict(path):
    bundle = json.loads(path.read_text())
    got = assess_history(bundle, bundle["trusted_public_key"])
    assert got.verdict == bundle["expect"]["verdict"], f"{path.name}: {got.reason}"
    assert got.valid == (got.verdict == "consistent")


def test_corpus_is_present():
    """A missing corpus must not pass as an empty parametrisation."""
    assert len(BUNDLES) >= 11, f"expected the adversary corpus at {ADV}"


def test_lag_is_not_backdating_is_pinned_as_consistent():
    """The honest limit, stated as a test so nobody 'improves' it away: a record
    absent from an earlier head is not evidence of backdating, because log order
    is submission order."""
    b = json.loads((ADV / "a3-lag-is-not-backdating.json").read_text())
    assert assess_history(b, b["trusted_public_key"]).verdict == "consistent"


def test_precedence_equivocation_before_fork():
    """A bundle with two faults must name the more serious one, and both
    implementations must agree on the order. Equivocation outranks a fork."""
    eq = json.loads((ADV / "a1-equivocation-same-size.json").read_text())
    fork = json.loads((ADV / "a1-fork-no-extension.json").read_text())
    both = {
        "trusted_public_key": eq["trusted_public_key"],
        "heads": eq["heads"] + fork["heads"],
        "consistency": fork["consistency"],
    }
    assert assess_history(both, both["trusted_public_key"]).verdict == "equivocation"


def test_per_org_heads_are_refused_in_a_bundle():
    """Only public heads carry the signing timestamp the A3 rule needs."""
    b = json.loads((ADV / "a1-consistent-growth.json").read_text())
    h = dict(b["heads"][0]); h.pop("log"); h["org_id"] = "org-x"
    got = assess_history({**b, "heads": [h]}, b["trusted_public_key"])
    assert got.verdict == "invalid_head"
